version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo_container2
    restart: always
    environment:
      MONGO_INITDB_DATABASE: family_tree
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
