export enum ChatBack {
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  OFFLINE = 'OFFLINE',
  ONLINE = 'ONLINE',
  SEND_MESSAGE = 'SEND_MESSAGE',
  REMOVE_MESSAGE = 'REMOVE_MESSAGE',
  UPDATE_MESSAGE = 'UPDATE_MESSAGE',
}

export enum ChatFront {
  LIST_USERS_ONLINE = 'LIST_USERS_ONLINE',
  PRIVATE_MESSAGE = 'PRIVATE_MESSAGE',
  NEW_MESSAGE = 'NEW_MESSAGE',
  ID_DELETE_MESSAGE = 'ID_DELETE_MESSAGE',
  ID_EDIT_MESSAGE = 'ID_EDIT_MESSAGE',
}

export enum Afk {
  ONLINE = 'online',
  OFFLINE = 'offline',
}
